### PR TITLE
Mostly remove cutscenes from temple

### PR DESCRIPTION
**Pull request by Dystopia-user181**
Temple has been widely criticised for having annoying cutscenes so most of them are now shortened to within 10 seconds.

### CODE REVIEW

**Comment by landgreen** [comment]
ok I'll add to next patch.

**Comment by Dystopia-user181** [comment]
You forgot to add to next patch

**Comment by landgreen** [comment]
I remember adding it.  But you are on the newest version of the game and you don't see the changes?
I just checked n-gon github and the changes seem to be there.

**Comment by Dystopia-user181** [comment]
Nevermind, the changes didn't load properly for me. I see them now

**Pull request closed without merging**
