### PR TITLE
Service Worker Atempt 2

### PR DESCRIPTION
**Pull request by Erisfiregamer1**
"text rewording" broke the old branch :(
Adds a service worker to N-gon. This allows it to be played offline from the github.io URL.
Can be modified to serve other sites.

### CODE REVIEW

**Comment by Erisfiregamer1** [comment]
When's this going to be reviewed?

**Comment by Erisfiregamer1** [comment]
It's been so long now I'm starting to believe I'm never going to have this merged.

**Comment by landgreen** [comment]
Sorry I don't check this repository often.  You can play n-gon offline by clicking "save page as"  I think the hot key is cmd-S or ctrl-S.

**Comment by Erisfiregamer1** [comment]
Went stale, eh?

**Comment by nreef12** [comment]
> I'm aware of this. This is a little more easy to use, though- one page entry and you'll be able to open the link offline.
> Also, that doesn't work on Chromebooks, a common device.

Sorry if I'm necroposting but you can download the source code to play it offline on a Chromebook.

**Comment by Erisfiregamer1** [comment]
> > I'm aware of this. This is a little more easy to use, though- one page entry and you'll be able to open the link offline.
> > Also, that doesn't work on Chromebooks, a common device.
> 
> Sorry if I'm necroposting but you can download the source code to play it offline on a Chromebook.

That's an annoyance. The service worker just does that silently and automatically.

**Pull request closed without merging**
