### PR TITLE
Add map

### PR DESCRIPTION
**Pull request by Whyisthisnotavalable**

### CODE REVIEW

**Comment by Whyisthisnotavalable** [comment]
Map speedrun

**Comment by Whyisthisnotavalable** [comment]
I made a mistake level.exit.y is supposed to be 3770

**Comment by landgreen** [comment]
This seems to have performance issues.  Maybe remove the text, or only write the text and web link when the player is nearby.  Also maybe shrink the map size,  there are too many blocks.  As it is now I can't upload it.

**Comment by landgreen** [comment]
You could also reduce the total blocks by making repeating sections of squares long rectangles.

**Comment by landgreen** [comment]
another issue, it seems you are widening the player foot detection region, but not resetting it to normal at the end of the level.

**Comment by Whyisthisnotavalable** [comment]
> This seems to have performance issues. Maybe remove the text, or only write the text and web link when the player is nearby. Also maybe shrink the map size, there are too many blocks. As it is now I can't upload it.

I do? It doesn't lag for me, are you referring to when you enter the map?

**Comment by landgreen** [comment]
I got lag in the maze and at the start of the map.  Matter.js doesn't like that many different bodies.  Also just drawing that many different squares can hurt performance.  (all that aside, it's a cool map)

**Comment by Whyisthisnotavalable** [comment]
I made it so that it spawns sections of long rectangles, but I'm still not sure how to reset the player foot.

**Comment by landgreen** [comment]
looks like you use this to widen the foot sensor
                Matter.Body.scale(player.parts[3], 2, 2);
you can undo that with 
                Matter.Body.scale(player.parts[3], 1/2, 1/2);
maybe run it when you can tell the player has left the maze

**Pull request closed without merging**
